# Generated by Django 3.2.13 on 2022-07-01 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('charger_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargingProcedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parked_from', models.DateTimeField(auto_now=True)),
                ('parked_until', models.DateTimeField(default=None, null=True)),
                ('charging_state', models.IntegerField(verbose_name=3)),
                ('needs_relocation', models.BooleanField(default=False)),
                ('is_pickedup', models.BooleanField(default=False)),
                ('charger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='charger_management.charger')),
                ('license_plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charger_management.car')),
                ('pool', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='charger_management.pool')),
            ],
        ),
    ]
