# Generated by Django 3.2.13 on 2022-07-04 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chargingprocedure',
            old_name='license_plate',
            new_name='car',
        ),
    ]
